name: CardsAgainstHumanity
main: com.gmail.xendroidzx.cah.CAH
version: 0.1.3
description: Cards Against Humanity in Minecraft
commands:
  cah:
    description: Base command for CardsAgainstHumanity
    aliases: [cardsagainsthumanity]
  czar:
    description: Show who the current Czar is